name: Build and Deploy Flutter Web to S3

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: portfolio_env

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: |
        rm pubspec.lock
        flutter clean
        flutter pub get
        flutter build -v web --release
        echo ${{ secrets.S3_TARGET }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: AWS steps
      run: | 
        aws s3 sync build/web/ ${{ secrets.S3_TARGET }} --acl public-read
        aws s3api put-object-acl \
          --bucket ${{ secrets.S3_TARGET }} \
          --key Latest_Vitucal_Resume.pdf --acl public-read
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DIST_ID }} --paths "/*"
