name: Build and Deploy Flutter Web to S3

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        # flutter-version: '2.0.5'
    - run: flutter pub get
    # - run: flutter test
    - run: |
        ls
        flutter build -v web --release
        ls build/web

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1  # change to your region

    # - name: Sync to S3
    #   run: aws s3 sync build/web s3://your-bucket-name --delete

